### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-1-infografia-MarleneRamirez0731#1]
![infografia_MarleneOsorio](https://github.com/user-attachments/assets/888410ab-ac48-4fb6-8951-950615378ad6)

**Comment by Jaczibeth** [comment]
De acuerdo a la rubrica tienes un 19% 
presentas falta de conceptos , dentro de lo demás se cumple

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
